import type {
  Mine,
  ComplianceItem,
  Inspection,
  Observation,
  Violation,
  CorrectiveAction,
  Alert,
  DashboardStats,
  ComplianceTrendPoint,
  RegionData,
} from '@/types';

export const mockDashboardStats: DashboardStats = {
  totalMines: 6,
  activeMines: 3,
  complianceRate: 74.2,
  openViolations: 6,
  pendingInspections: 2,
  activeAlerts: 3,
  totalObservations: 5,
  correctiveActionsInProgress: 5,
};

export const mockMines: Mine[] = [
  {
    id: 'MOC-66',
    code: 'MOC-66',
    name: 'Choritand Tilaya Block',
    location: 'Bokaro, Jharkhand',
    state: 'Jharkhand',
    district: 'Bokaro',
    coalGrade: 'C',
    type: 'opencast',
    status: 'active',
    complianceScore: 91,
    complianceLevel: 'compliant',
    workforce: 1820,
    productionTarget: 5400,
    productionAchieved: 5060,
    lastInspection: '2026-08-18',
    nextInspection: '2026-09-22',
    openViolations: 1,
    area: 820,
    operator: 'BCCL',
    reserves: 1240,
  },
  {
    id: 'MOC-67',
    code: 'MOC-67',
    name: 'Jogeshwar Coal Block',
    location: 'Hazaribagh, Jharkhand',
    state: 'Jharkhand',
    district: 'Hazaribagh',
    coalGrade: 'B',
    type: 'underground',
    status: 'under_review',
    complianceScore: 68,
    complianceLevel: 'warning',
    workforce: 980,
    productionTarget: 3100,
    productionAchieved: 2240,
    lastInspection: '2026-08-01',
    nextInspection: '2026-09-12',
    openViolations: 3,
    area: 450,
    operator: 'CCL',
    reserves: 680,
  },
  {
    id: 'MOC-68',
    code: 'MOC-68',
    name: 'Rabodh Block',
    location: 'Hazaribagh, Jharkhand',
    state: 'Jharkhand',
    district: 'Hazaribagh',
    coalGrade: 'D',
    type: 'mixed',
    status: 'active',
    complianceScore: 84,
    complianceLevel: 'compliant',
    workforce: 1240,
    productionTarget: 4200,
    productionAchieved: 3890,
    lastInspection: '2026-08-10',
    nextInspection: '2026-09-18',
    openViolations: 2,
    area: 610,
    operator: 'CCL',
    reserves: 890,
  },
  {
    id: 'MOC-69',
    code: 'MOC-69',
    name: 'Rohne Coal Block',
    location: 'Ramgarh, Jharkhand',
    state: 'Jharkhand',
    district: 'Ramgarh',
    coalGrade: 'C',
    type: 'opencast',
    status: 'suspended',
    complianceScore: 52,
    complianceLevel: 'critical',
    workforce: 760,
    productionTarget: 2800,
    productionAchieved: 1120,
    lastInspection: '2026-07-14',
    nextInspection: '2026-09-08',
    openViolations: 5,
    area: 380,
    operator: 'Private Operator',
    reserves: 520,
  },
  {
    id: 'MOC-70',
    code: 'MOC-70',
    name: 'Urtan North Coal Block',
    location: 'Shahdol, Madhya Pradesh',
    state: 'Madhya Pradesh',
    district: 'Shahdol',
    coalGrade: 'E',
    type: 'opencast',
    status: 'active',
    complianceScore: 87,
    complianceLevel: 'compliant',
    workforce: 1540,
    productionTarget: 4600,
    productionAchieved: 4210,
    lastInspection: '2026-08-22',
    nextInspection: '2026-09-28',
    openViolations: 0,
    area: 590,
    operator: 'SECL',
    reserves: 960,
  },
  {
    id: 'MOC-71',
    code: 'MOC-71',
    name: 'North of Arkhapal and Srirampur Coal Block',
    location: 'Chandrapur, Maharashtra',
    state: 'Maharashtra',
    district: 'Chandrapur',
    coalGrade: 'F',
    type: 'mixed',
    status: 'under_review',
    complianceScore: 63,
    complianceLevel: 'critical',
    workforce: 1100,
    productionTarget: 3600,
    productionAchieved: 2480,
    lastInspection: '2026-07-26',
    nextInspection: '2026-09-10',
    openViolations: 4,
    area: 720,
    operator: 'WCL',
    reserves: 840,
  },
];

export const mockComplianceItems: ComplianceItem[] = [
  {
    id: 'C001',
    mineId: 'MOC-67',
    mineName: 'Jogeshwar Coal Block',
    regulation: 'CMR 2024 - Reg 99',
    description: 'Ventilation system inspection overdue',
    level: 'warning',
    dueDate: '2026-09-12',
    status: 'warning',
  },
  {
    id: 'C002',
    mineId: 'MOC-69',
    mineName: 'Rohne Coal Block',
    regulation: 'CMR 2024 - Reg 73',
    description: 'Support system certification expired',
    level: 'critical',
    dueDate: '2026-09-05',
    status: 'critical',
  },
  {
    id: 'C003',
    mineId: 'MOC-71',
    mineName: 'North of Arkhapal and Srirampur Coal Block',
    regulation: 'EPA 1986 - Air Quality',
    description: 'Particulate emission limits exceeded',
    level: 'critical',
    dueDate: '2026-08-30',
    status: 'critical',
  },
  {
    id: 'C004',
    mineId: 'MOC-66',
    mineName: 'Choritand Tilaya Block',
    regulation: 'CMR 2024 - Reg 112',
    description: 'Emergency evacuation drill records verified',
    level: 'compliant',
    dueDate: '2026-08-15',
    status: 'compliant',
  },
  {
    id: 'C005',
    mineId: 'MOC-68',
    mineName: 'Rabodh Block',
    regulation: 'CMR 2024 - Reg 66',
    description: 'Dust suppression system pending review',
    level: 'warning',
    dueDate: '2026-09-22',
    status: 'warning',
  },
];

export const mockInspections: Inspection[] = [
  {
    id: 'I001',
    mineId: 'MOC-67',
    mineName: 'Jogeshwar Coal Block',
    date: '2026-09-12',
    type: 'safety',
    inspector: 'R. Subramanian',
    status: 'scheduled',
    observations: 0,
    violations: 0,
  },
  {
    id: 'I002',
    mineId: 'MOC-69',
    mineName: 'Rohne Coal Block',
    date: '2026-09-05',
    type: 'compliance',
    inspector: 'A. Mehta',
    status: 'in_progress',
    observations: 8,
    violations: 3,
  },
  {
    id: 'I003',
    mineId: 'MOC-71',
    mineName: 'North of Arkhapal and Srirampur Coal Block',
    date: '2026-07-26',
    type: 'environmental',
    inspector: 'S. Nair',
    status: 'completed',
    observations: 12,
    violations: 5,
  },
  {
    id: 'I004',
    mineId: 'MOC-70',
    mineName: 'Urtan North Coal Block',
    date: '2026-08-22',
    type: 'operational',
    inspector: 'P. Reddy',
    status: 'completed',
    observations: 6,
    violations: 1,
  },
  {
    id: 'I005',
    mineId: 'MOC-66',
    mineName: 'Choritand Tilaya Block',
    date: '2026-08-18',
    type: 'safety',
    inspector: 'K. Dasgupta',
    status: 'completed',
    observations: 4,
    violations: 0,
  },
  {
    id: 'I006',
    mineId: 'MOC-68',
    mineName: 'Rabodh Block',
    date: '2026-08-10',
    type: 'safety',
    inspector: 'R. Subramanian',
    status: 'completed',
    observations: 3,
    violations: 1,
  },
];

export const mockObservations: Observation[] = [
  {
    id: 'O001',
    mineId: 'MOC-69',
    mineName: 'Rohne Coal Block',
    inspectionId: 'I002',
    category: 'Structural Support',
    description: 'Roof bolt density below required standard in Section B-12',
    severity: 'high',
    status: 'open',
    createdAt: '2026-09-04',
  },
  {
    id: 'O002',
    mineId: 'MOC-69',
    mineName: 'Rohne Coal Block',
    inspectionId: 'I002',
    category: 'Gas Detection',
    description: 'Methane levels approaching threshold in ventilation shaft 3',
    severity: 'critical',
    status: 'acknowledged',
    createdAt: '2026-09-04',
  },
  {
    id: 'O003',
    mineId: 'MOC-71',
    mineName: 'North of Arkhapal and Srirampur Coal Block',
    inspectionId: 'I003',
    category: 'Air Quality',
    description: 'PM10 readings 40% above permissible limit at east boundary',
    severity: 'high',
    status: 'open',
    createdAt: '2026-07-26',
  },
  {
    id: 'O004',
    mineId: 'MOC-71',
    mineName: 'North of Arkhapal and Srirampur Coal Block',
    inspectionId: 'I003',
    category: 'Water Management',
    description: 'Settling pond overflow during monsoon runoff',
    severity: 'medium',
    status: 'resolved',
    createdAt: '2026-07-26',
  },
  {
    id: 'O005',
    mineId: 'MOC-70',
    mineName: 'Urtan North Coal Block',
    inspectionId: 'I004',
    category: 'Equipment Safety',
    description: 'Dragline cable insulation showing wear in two sections',
    severity: 'low',
    status: 'resolved',
    createdAt: '2026-08-22',
  },
];

export const mockViolations: Violation[] = [
  {
    id: 'V001',
    mineId: 'MOC-69',
    mineName: 'Rohne Coal Block',
    regulation: 'CMR 2024 - Reg 73',
    description: 'Inadequate roof support in working section B-12',
    severity: 'high',
    penalty: 250000,
    status: 'open',
    date: '2026-09-04',
  },
  {
    id: 'V002',
    mineId: 'MOC-71',
    mineName: 'North of Arkhapal and Srirampur Coal Block',
    regulation: 'EPA 1986 - Air Quality',
    description: 'Exceeding particulate emission standards',
    severity: 'critical',
    penalty: 500000,
    status: 'open',
    date: '2026-07-27',
  },
  {
    id: 'V003',
    mineId: 'MOC-69',
    mineName: 'Rohne Coal Block',
    regulation: 'CMR 2024 - Reg 99',
    description: 'Ventilation quantity below minimum required airflow',
    severity: 'high',
    penalty: 200000,
    status: 'open',
    date: '2026-07-14',
  },
  {
    id: 'V004',
    mineId: 'MOC-67',
    mineName: 'Jogeshwar Coal Block',
    regulation: 'CMR 2024 - Reg 112',
    description: 'Emergency evacuation drill not conducted in Q2',
    severity: 'medium',
    penalty: 100000,
    status: 'open',
    date: '2026-08-01',
  },
  {
    id: 'V005',
    mineId: 'MOC-68',
    mineName: 'Rabodh Block',
    regulation: 'CMR 2024 - Reg 66',
    description: 'Dust suppression water pressure insufficient at conveyor 4',
    severity: 'low',
    penalty: 50000,
    status: 'open',
    date: '2026-08-10',
  },
  {
    id: 'V006',
    mineId: 'MOC-66',
    mineName: 'Choritand Tilaya Block',
    regulation: 'CMR 2024 - Reg 55',
    description: 'Minor signage deficiency at haul road intersection',
    severity: 'low',
    penalty: 25000,
    status: 'open',
    date: '2026-08-18',
  },
];

export const mockCorrectiveActions: CorrectiveAction[] = [
  {
    id: 'CA001',
    mineId: 'MOC-69',
    mineName: 'Rohne Coal Block',
    relatedViolationId: 'V001',
    description: 'Install additional roof bolts in Section B-12 per revised density plan',
    assignedTo: 'Engineering Team - Rohne',
    dueDate: '2026-09-20',
    progress: 35,
    status: 'in_progress',
  },
  {
    id: 'CA002',
    mineId: 'MOC-71',
    mineName: 'North of Arkhapal and Srirampur Coal Block',
    relatedViolationId: 'V002',
    description: 'Install additional electrostatic precipitators at east boundary',
    assignedTo: 'Environmental Compliance Unit',
    dueDate: '2026-10-01',
    progress: 20,
    status: 'in_progress',
  },
  {
    id: 'CA003',
    mineId: 'MOC-69',
    mineName: 'Rohne Coal Block',
    relatedViolationId: 'V003',
    description: 'Upgrade main ventilation fan capacity to meet airflow requirements',
    assignedTo: 'Mechanical Engineering Division',
    dueDate: '2026-09-15',
    progress: 50,
    status: 'in_progress',
  },
  {
    id: 'CA004',
    mineId: 'MOC-67',
    mineName: 'Jogeshwar Coal Block',
    relatedViolationId: 'V004',
    description: 'Schedule and execute Q2 emergency evacuation drill',
    assignedTo: 'Safety Officer - Jogeshwar',
    dueDate: '2026-09-10',
    progress: 10,
    status: 'in_progress',
  },
  {
    id: 'CA005',
    mineId: 'MOC-68',
    mineName: 'Rabodh Block',
    relatedViolationId: 'V005',
    description: 'Replace and recalibrate dust suppression water pump at conveyor 4',
    assignedTo: 'Maintenance Team - Rabodh',
    dueDate: '2026-09-05',
    progress: 60,
    status: 'in_progress',
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 'A001',
    mineId: 'MOC-69',
    mineName: 'Rohne Coal Block',
    type: 'safety',
    title: 'Methane Gas Threshold Alert',
    description: 'Methane concentration approaching 1.2% in ventilation shaft 3. Immediate action required.',
    severity: 'critical',
    timestamp: '2026-09-06T08:32:00',
    acknowledged: false,
  },
  {
    id: 'A002',
    mineId: 'MOC-71',
    mineName: 'North of Arkhapal and Srirampur Coal Block',
    type: 'environmental',
    title: 'Particulate Emission Exceeded',
    description: 'PM10 levels 40% above permissible limit at east boundary monitoring station.',
    severity: 'high',
    timestamp: '2026-09-06T06:15:00',
    acknowledged: false,
  },
  {
    id: 'A003',
    mineId: 'MOC-67',
    mineName: 'Jogeshwar Coal Block',
    type: 'ai_prediction',
    title: 'AI Predicted Structural Risk',
    description: 'AI model predicts 78% probability of roof instability in Section C-7 within 14 days.',
    severity: 'high',
    timestamp: '2026-09-05T22:45:00',
    acknowledged: true,
  },
  {
    id: 'A004',
    mineId: 'MOC-69',
    mineName: 'Rohne Coal Block',
    type: 'compliance',
    title: 'Support Certification Expired',
    description: 'Structural support system certification expired on 2026-09-01. Renewal required.',
    severity: 'medium',
    timestamp: '2026-09-05T14:00:00',
    acknowledged: false,
  },
  {
    id: 'A005',
    mineId: 'MOC-70',
    mineName: 'Urtan North Coal Block',
    type: 'operational',
    title: 'Production Target Behind Schedule',
    description: 'Current production at 92% of target. Dragline downtime identified as primary cause.',
    severity: 'low',
    timestamp: '2026-09-05T09:20:00',
    acknowledged: true,
  },
];

export const mockComplianceTrend: ComplianceTrendPoint[] = [
  { month: 'Apr', compliance: 82, violations: 31, inspections: 14 },
  { month: 'May', compliance: 84, violations: 28, inspections: 16 },
  { month: 'Jun', compliance: 83, violations: 30, inspections: 12 },
  { month: 'Jul', compliance: 86, violations: 26, inspections: 18 },
  { month: 'Aug', compliance: 88, violations: 24, inspections: 15 },
  { month: 'Sep', compliance: 87, violations: 23, inspections: 12 },
];

export const mockRegionData: RegionData[] = [
  { region: 'Jharkhand', mines: 4, compliance: 79, violations: 4 },
  { region: 'Madhya Pradesh', mines: 1, compliance: 87, violations: 0 },
  { region: 'Maharashtra', mines: 1, compliance: 63, violations: 2 },
];
